### ISSUE TITLE
AssertionError: An object named 'L1Loss' was already registered in 'loss' registry!

### ISSUE THREAD

**Issue by laidingq** [ShmuelRonen/ComfyUI_wav2lip#1]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 14, in <module>
    from custom_nodes.ComfyUI_wav2lip.facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 37, in <module>
    from custom_nodes.ComfyUI_wav2lip.basicsr.utils.registry import ARCH_REGISTRY
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\basicsr\__init__.py", line 5, in <module>
    from .losses import *
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\basicsr\losses\__init__.py", line 5, in <module>
    from .losses import (CharbonnierLoss, GANLoss, L1Loss, MSELoss, PerceptualLoss, WeightedTVLoss, g_path_regularize,
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\basicsr\losses\losses.py", line 30, in <module>
    @LOSS_REGISTRY.register()
     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\facerestore_cf\basicsr\utils\registry.py", line 53, in deco
    self._do_register(name, func_or_class)
  File "D:\ComfyUI\custom_nodes\facerestore_cf\basicsr\utils\registry.py", line 39, in _do_register
    assert (name not in self._obj_map), (f"An object named '{name}' was already registered "
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: An object named 'L1Loss' was already registered in 'loss' registry!

Cannot import D:\ComfyUI\custom_nodes\ComfyUI_wav2lip module for custom nodes: An object named 'L1Loss' was already registered in 'loss' registry!

**Comment by ShmuelRonen** [comment]
Made a fix. please git pull

**Comment by ShmuelRonen** [comment]
Open the 'basicsr' folder in the repository (here) and navigate to basicsr\utils folder. download the file registry.py and replace it in your ComfyUI_wav2lip\basicsr\utils folder.

**Comment by laidingq** [comment]
Now that I have deleted it and restarted the git clone, the error still exists

**Comment by ShmuelRonen** [comment]
[registry.txt](https://github.com/ShmuelRonen/ComfyUI_wav2lip/files/15303129/registry.txt)

Change the name of this file to registry.py and put it in your custom_nodes\ComfyUI_wav2lip\basicsr\utils folder

**Comment by laidingq** [comment]
> [registry.txt](https://github.com/ShmuelRonen/ComfyUI_wav2lip/files/15303129/registry.txt)
> 
> Change the name of this file to registry.py and put it in your custom_nodes\ComfyUI_wav2lip\basicsr\utils folder

Error still reported after replacement

**Comment by ShmuelRonen** [comment]
Try to performing hard refresh on ComfyUI with ctrl+F5

**Comment by laidingq** [comment]
> 尝试使用 ctrl+F5 在 ComfyUI 上执行硬刷新

without effect

**Comment by ShmuelRonen** [comment]
Try to install this custom node and tell me if it work's for you:

https://github.com/mav-rik/facerestore_cf

**Comment by laidingq** [comment]
> 尝试安装此自定义节点并告诉我它是否适合您：
> 
> https://github.com/mav-rik/facerestore_cf

This plugin can be installed correctly

**Comment by ShmuelRonen** [comment]
Also I update now the registry.py

**Comment by laidingq** [comment]
Same error after update

**Comment by laidingq** [comment]
The error still exists,
My Python=3.11.8 torch2.1.2+cu121  win11

**Comment by ShmuelRonen** [comment]
Send me the all ComfyUI CMD log

**Comment by laidingq** [comment]
[comfyui.log](https://github.com/ShmuelRonen/ComfyUI_wav2lip/files/15306728/comfyui.log)

**Comment by ShmuelRonen** [comment]
Update now the registry.py please check it out

**Comment by laidingq** [comment]
> 立即更新registry.py，请查看

Unable to load

**Comment by ShmuelRonen** [comment]
[registry.txt](https://github.com/ShmuelRonen/ComfyUI_wav2lip/files/15307481/registry.txt)

Change the name of this file to registry.py and put it in your custom_nodes\ComfyUI_wav2lip\basicsr\utils folder

**Comment by laidingq** [comment]
> [注册表.txt](https://github.com/ShmuelRonen/ComfyUI_wav2lip/files/15307481/registry.txt)
> 
> 将此文件的名称更改为registry.py并将其放入您的custom_nodes\ComfyUI_wav2lip\basicsr\utils文件夹中

The same question

**Comment by ShmuelRonen** [comment]
You can try now

**Comment by laidingq** [comment]
The same question

> You can try now

**Comment by ShmuelRonen** [comment]
There are solution for your error please: git pull

**Comment by laidingq** [comment]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 33, in <module>
    from wav2lip import Wav2Lip
ModuleNotFoundError: No module named 'wav2lip'

**Comment by ShmuelRonen** [comment]
Add now dynamic path recognizing to wav2lip.py

**Comment by ShmuelRonen** [comment]
Try the new fix of wav2lip.py

**Comment by laidingq** [comment]
![image](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/135723102/cece2a99-ed6a-4bdc-acdd-a0af462786f3)

**Comment by laidingq** [comment]
Successfully loaded, found incorrect menu display name

**Comment by ShmuelRonen** [comment]
Add path dynamic allocation to wav2lip.py please git pull

**Comment by laidingq** [comment]
![image](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/135723102/b5dc3cb5-6f7a-40ae-8d5d-67eae4df0d1c)
The following problems were found: 
1. The menu name is incorrect
2. I need to download the model first before it can be loaded successfully

**Comment by laidingq** [comment]
Here are my suggestions. If you find it useful, you can adopt it.

facerestore_models and facedetection_mode are also used in other plug-ins. In order to avoid repeated downloads taking up space, it is recommended to unify the paths of the models.
facedetection_mode:ComfyUI\models\facedetection\

facerestore_models:ComfyUI\models\facerestore_models\

wav2lip model:ComfyUI\models\wav2lip\
