### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by vootox** [ShmuelRonen/ComfyUI_wav2lip#13]
When I tried installing it with ComfyUI manager there was an error "(IMPORT FAILED)"

So I tried Windows CMD to clone but there was a "Git Credentials Authentication" window that popped up.

**Comment by ShmuelRonen** [comment]
```
git clone https://github.com/ShmuelRonen/ComfyUI_wav2lip.git
 ```

I try it now:
 ```
C:\>git clone https://github.com/ShmuelRonen/ComfyUI_wav2lip.git
Cloning into 'ComfyUI_wav2lip'...
remote: Enumerating objects: 452, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 452 (delta 106), reused 39 (delta 38), pack-reused 284
Receiving objects: 100% (452/452), 1.49 MiB | 3.64 MiB/s, done.
Resolving deltas: 100% (173/173), done.

C:\>
 ```

**Comment by vootox** [comment]
Thank you for your work and help. The clone is working but the node is still not there. 
![Screenshot 2024-05-21 180526](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/27273724/53f7d224-4f7a-44ff-afe8-a61ae3c15c13)
![Screenshot 2024-05-21 180622](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/27273724/c8678c13-a52a-4d5d-a172-c006ece08772)

**Comment by vootox** [comment]
> Send me the CMD log of your ComfyUI

"assert model_exists, f"Model {wav2lip_model_file} not found in {checkpoints_path}"

Thank you for mentioning the log! I never realized the node would not show without the model. The model was the very first thing I had downloaded but somehow I had entirely forgotten to include it. Thank you for your patience, my age is catching up with me I think, my mistake.
