### ISSUE TITLE
תמיכה במודל Wav2Lip

### ISSUE THREAD

**Issue by start-life** [ShmuelRonen/ComfyUI_wav2lip#15]
זה תומך גם במודל Wav2Lip או רק בwav2lip_gan? והאם תוכל להוסיף תמיכה גם במודל Wav2Lip?

**Comment by start-life** [comment]
> wav2lip

בWav2Lip כותבים שבמודל הזה יש סינכרון שפתיים מדויק ביותר, יותר ממודל wav2lip_gan שנותן סינכרון שפתיים נחות במקצת, אך איכות חזותית טובה יותר

**Comment by ShmuelRonen** [comment]
תצטרך לשנות את שמו ל wav2lip_gan.pth כדי שיזוהה
