### ISSUE TITLE
זה לא עובד כבר יותר משעה אני ממתין לתוצאות

### ISSUE THREAD

**Issue by start-life** [ShmuelRonen/ComfyUI_wav2lip#16]
כבר יותר משעה אני ממתין לתוצאה וזה תקוע בצומת video combine
זה לא בגלל מפרט המחשC שלי, יש לי 16 RAM וכרטיס גרפי RTX3070

![צילום מסך 2024-05-21 164649](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/96779864/a38b03af-5478-401b-bea8-1e09d8648230)

פלט יומן:
To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
(80, 2636)
Length of mel chunks: 984
Load model from: C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints\wav2lip_gan.pth
Load checkpoint from: C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints\wav2lip_gan.pth
100%|████████████████████████████████████████████████████████████████████████████████| 105/105 [00:50<00:00,  2.10it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:12<00:00,  9.07s/it]
out_images len = 984

**Comment by ShmuelRonen** [comment]
תנסה את הגרסה שתיקנתי.  יש הסבר בדף בסוף

**Comment by ShmuelRonen** [comment]
Fix Video combine node endless loop
In case of an endless loop in the VideoCombine node when you connect audio to the node, you can download the 7zip file containing the fixed node from the ComfyUI-VideoHelperSuite-fix folder in the repository and replace the existing one.

In the repository there are ComfyUI-VideoHelperSuite-fix folder.
find the ComfyUI-VideoHelperSuite.7zip file in the folder.
Extract the contents of the ComfyUI-VideoHelperSuite.7zip folder to a temporary location on your computer.
Locate the existing ComfyUI-VideoHelperSuite node in your ComfyUI/custom_nodes folder.
Replace the existing ComfyUI-VideoHelperSuite node with the fix one.
Restart ComfyUI to apply the changes.

**Comment by start-life** [comment]
ראיתי אני בודק את זה עכשיו
