### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by mike-rowley** [ShmuelRonen/ComfyUI_wav2lip#20]
I am getting the following error in the ComfyUI log when it loads:

Base directory: /mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip
Checkpoints path: /mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/Wav2Lip/checkpoints
Model path: /mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/Wav2Lip/checkpoints/wav2lip_gan.pth
Wav2Lip path added to sys.path: /mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip
Directory created or exists: /mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/facedetection
Current directory: /mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip
Wav2Lip path: /mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip
Traceback (most recent call last):
  File "/mnt/wf/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip.py", line 56, in <module>
    from wav2lip_node import wav2lip_
ModuleNotFoundError: No module named 'wav2lip_node'

Cannot import /mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip module for custom nodes: No module named 'wav2lip_node'

Any suggestions?  I looked through existing Issues and nothing seemed to match.

**Comment by ShmuelRonen** [comment]
It looks like the code can't find wav2lip_node.py in ComfyUI_wav2lip\wav2lip. Since this node works well for many users, please try to reinstalling the node again.

**Comment by mike-rowley** [comment]
I have reinstalled via the Manager and manually through a git pull with the same result.

I can't see how changing the string in a printf statement alters the code execution, it will just change the text in the comfy execution console

**Comment by ShmuelRonen** [comment]
> It looks like the code can't find wav2lip_node.py in ComfyUI_wav2lip\Wav2lip. Since this node works well for many users, it's maybe a Linux problem. perhaps use in capital letter 'Wav2lip'
> 
> try to change the name of this directory to wav2lip and make a little change in wav2lip.py in line 48
> 
> from:
> 
> print(f"Wav2Lip path added to sys.path: {wav2lip_path}")
> 
> to:
> 
> print(f"wav2Lip path added to sys.path: {wav2lip_path}")

It looks like the code can't find wav2lip_node.py in ComfyUI_wav2lip\Wav2lip. Since this node works well for many users, it's maybe a Linux problem. perhaps use in capital letter 'Wav2lip'

try to change the name of this directory to wav2lip and make a little change in wav2lip.py in line 48

from:

print(f"Wav2Lip path added to sys.path: {wav2lip_path}")

to:

print(f"wav2Lip path added to sys.path: {wav2lip_path}")

**Comment by mike-rowley** [comment]
Ah I understand, change the directory and not the code.  And yes that resolves the issue.  The capitol letters on Linux were the issue.  Thanks for the assistance, I am assuming you will change this in the code base in the future?

**Comment by ShmuelRonen** [comment]
It's bigger than that. I make the change and put it in the repository.

**Comment by ShmuelRonen** [comment]
ok. I give you a test to check if it's will work for you on Linux.

1. change the name of to folder Wav2lip to wav2lip.
2. change the name of this code from wav2lip.txt to wav2lip.py and replace the new file with the new one:
[wav2lip.txt](https://github.com/ShmuelRonen/ComfyUI_wav2lip/files/15407528/wav2lip.txt)
3. in the folder wav2lip replace this file after you change from .txt to .py:
[wav2lip_node.txt](https://github.com/ShmuelRonen/ComfyUI_wav2lip/files/15407544/wav2lip_node.txt)
4. Restart ComfyUI

Let me know if it works for you.

**Comment by mike-rowley** [comment]
I made the 3 changes and Import Failed with this error:

Traceback (most recent call last):
  File "/mnt/wf/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip.py", line 15, in <module>
    from .facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from custom_nodes.ComfyUI_wav2lip.facelib.detection import init_detection_model
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip.py", line 15, in <module>
    from .facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from custom_nodes.ComfyUI_wav2lip.facelib.detection import init_detection_model
  File "/mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip/facelib/detection/__init__.py", line 7, in <module>
    from custom_nodes.facerestore_cf.facelib.utils import load_file_from_url
ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'

Cannot import /mnt/wf/ComfyUI/custom_nodes/ComfyUI_wav2lip module for custom nodes: No module named 'custom_nodes.facerestore_cf'

**Comment by ShmuelRonen** [comment]
I continue to look at it. In the meantime you can run it on ComfyUI on Windows if you have it.

**Comment by ShmuelRonen** [comment]
The folder 'basicsr' in path 'custom_nodes.ComfyUI_wav2lip.basicsr' not exist anymore!

It's looks like you use old version of ComfyUI_wav2lip or some other mismatch

**Comment by simonjaq** [comment]
Hi @ShmuelRonen I have the exact same issue on Ubuntu. Also tried your fix above and getting the same 'ModuleNotFoundError: No module named 'custom_nodes.ComfyUI_wav2lip.basicsr'' error.
Looks like a super useful node and would be great to get it to run.

**Comment by Uemuet** [comment]
> The folder 'basicsr' in path 'custom_nodes.ComfyUI_wav2lip.basicsr' not exist anymore!
> 
> It's looks like you use old version of ComfyUI_wav2lip or some other mismatch

I have the newest comfyui version

**Comment by ShmuelRonen** [comment]
> > The folder 'basicsr' in path 'custom_nodes.ComfyUI_wav2lip.basicsr' not exist anymore!
> > It's looks like you use old version of ComfyUI_wav2lip or some other mismatch
> 
> I have the newest comfyui version

ComfyUI_wav2lip latest version

**Comment by ksenia-portu** [comment]
I have got the same error on linux ( on NixOS)
```
    from wav2lip_node import wav2lip_
ModuleNotFoundError: No module named 'wav2lip_node'
```
The comfyui and your node are latest version

**Comment by ShmuelRonen** [comment]
> I have got the same error on linux ( on NixOS)
> 
> ```
>     from wav2lip_node import wav2lip_
> ModuleNotFoundError: No module named 'wav2lip_node'
> ```
> 
> The comfyui and your node are latest version

The wav2lip node is not compatible with Linux ComfyUI. sorry for that.
