### ISSUE TITLE
Hi there is a problem Cloning the repository (file not found) and also loading the wav2lip_gan.pth from the folder (C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints) it only fined the models in the folder (C:\ComfyUI_windows_portable\ComfyUI\models\facerestore_models)

### ISSUE THREAD

**Issue by gilushon** [ShmuelRonen/ComfyUI_wav2lip#30]
היי שמואל, תודה רבה על ה-NODE הנפלא, יש בעיה לתפעל אותו .....

Hi there is a problem Cloning the repository (file not found) and also loading the wav2lip_gan.pth from the folder (C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints) 
it only fined the models in the folder (C:\ComfyUI_windows_portable\ComfyUI\models\facerestore_models)

The only model that working is codeformer. 

The main error after doing all the installation steps is:

Error occurred when executing FaceRestoreModelLoader:

File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 293, in load_model
out = model_loading.load_state_dict(sd).eval()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\comfy_extras\chainner_models\model_loading.py", line 5, in load_state_dict
return ModelLoader().load_from_state_dict(state_dict).eval()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\spandrel\__helpers\loader.py", line 94, in load_from_state_dict
return self.registry.load(state_dict).to(self.device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\spandrel\__helpers\registry.py", line 184, in load
raise UnsupportedModelError

Close
Queue size: 0
⚙️
🖼️
×
Queue Prompt
Extra options
Queue FrontView QueueView History
Save
LoadRefresh
Clipspace
Clear
Load Default
Reset View
Manager
Share
spandrel.__helpers.registry.UnsupportedModelError 142 FaceRestoreModelLoader

מחכה לעזרה,  או תיקון, תודה רבה !!!

**Comment by ShmuelRonen** [comment]
Hi Gil. I also have the problem than in facerestore_cf node only codeformer works. 
Unfortunately the facerestore_cf node has not been updated for about 9 months and maybe because of that it probably having trouble functioning.

**Comment by gilushon** [comment]
Hi, so the only option is to use only the codeformer model? (it's not that good model...)
will you update your wa2lip project to work with all the models?

**Comment by ShmuelRonen** [comment]
I will try to figure it out.

**Comment by Kimthanh27** [comment]
Error occurred when executing FaceRestoreCFWithModel:

Unable to allocate 31.6 MiB for an array with shape (3840, 2160, 1) and data type int32

File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
Every time I use the face enhance flow, there is an issue with face restore. Have you found a solution yet?

**Comment by ShmuelRonen** [comment]
I fix it. try again
