### ISSUE TITLE
Cloning failed

### ISSUE THREAD

**Issue by jamiegrcn** [ShmuelRonen/ComfyUI_wav2lip#35]
Hey, got this error on cloning the repository to custom_nodes folder.
![image](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/174537364/e5986383-a7ad-4b02-8a7c-a129ff0f1b7f)

**Comment by jamiegrcn** [comment]
![image](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/174537364/a4ced6a8-2a5d-4116-a2eb-a811993e6c83)

Here is the cmd ComfyUI code

C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-03 11:24:11.953114
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\main.py
** Log path: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.8 seconds: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16306 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.43)
### ComfyUI Revision: 2310 [521421f5] | Released on '2024-06-30'
C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Base directory: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip
Checkpoints path: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints
Model path: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints\wav2lip_gan.pth
Traceback (most recent call last):
  File "C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 33, in <module>
    assert model_exists, f"Model {wav2lip_model_file} not found in {checkpoints_path}"
AssertionError: Model wav2lip_gan.pth not found in C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints

Cannot import C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip module for custom nodes: Model wav2lip_gan.pth not found in C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints

Import times for custom nodes:
   0.0 seconds: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip
   0.2 seconds: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
Install custom node 'Wav2Lip Node for ComfyUI'
Try fixing: ['https://github.com/ShmuelRonen/ComfyUI_wav2lip']
Install: pip packages
Attempt to fixing '['https://github.com/ShmuelRonen/ComfyUI_wav2lip']' is done.
After restarting ComfyUI, please refresh the browser.

Restarting... [Legacy Mode]



C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable>pause
Drücken Sie eine beliebige Taste . . . [START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-03 11:25:20.612286
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\main.py
** Log path: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   1.2 seconds: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16306 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.43)
### ComfyUI Revision: 2310 [521421f5] | Released on '2024-06-30'
C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Base directory: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip
Checkpoints path: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints
Model path: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints\wav2lip_gan.pth
Traceback (most recent call last):
  File "C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 33, in <module>
    assert model_exists, f"Model {wav2lip_model_file} not found in {checkpoints_path}"
AssertionError: Model wav2lip_gan.pth not found in C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints

Cannot import C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip module for custom nodes: Model wav2lip_gan.pth not found in C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints

Import times for custom nodes:
   0.0 seconds: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip
   0.2 seconds: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\jamie\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]

**Comment by ShmuelRonen** [comment]
I fix it. try again
