### ISSUE TITLE
Error:  'dict' object is not callable

### ISSUE THREAD

**Issue by bollerdominik** [ShmuelRonen/ComfyUI_wav2lip#36]
Hi

When I open the provided workflow ([wav2lip.json](https://github.com/ShmuelRonen/ComfyUI_wav2lip/blob/main/example/wav2lip.json)) I first get the error

> This workflow contains one or more nodes which use the old VHS_AUDIO format. They have been highlighted in red. An AudioToVHSAudio node must be added to convert to this legacy format

If I then ignore the error and continue to run it I get this error:

```
Error occurred when executing Wav2Lip:

'dict' object is not callable

  File "D:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 98, in process
    audio_data = process_audio(audio())
                               ^^^^^^^
```

**Comment by ShmuelRonen** [comment]
I can't reproduce the error you are getting:

![07 07 24-test](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/80190186/862859d7-1354-4aaf-89a0-7415a2e6e490)

**Comment by TomySpagnoletti** [comment]
Same error: 
<img width="1388" alt="Screenshot 2024-07-08 at 14 31 21" src="https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/9999608/184be073-370f-4118-a5ed-d101b9a51d00">

To reproduce, please update VHS

**Comment by TomySpagnoletti** [comment]
<img width="519" alt="Screenshot 2024-07-08 at 14 32 41" src="https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/9999608/ad632c95-b2db-4bb1-af1c-1842d23607f0">

Updated VHS Audio Node cannot connect to your node....

**Comment by TomySpagnoletti** [comment]
Here is the fix:
<img width="844" alt="Screenshot 2024-07-08 at 14 40 14" src="https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/9999608/a5db967e-6ccc-47c9-9071-b449491d4753">

From: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/commit/29fae7510ff113011b4e09a47a0676735ed4957f

**Comment by ShmuelRonen** [comment]
Please replace the folder 'ComfyUI-VideoHelperSuite' in custom_noads with the contain of the .7zip folder that in the repository.

![zip](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/80190186/99882a8a-b89e-402c-9968-3056e21a761b)

It's should solve the problem.

**Comment by bollerdominik** [comment]
Trying the fix from https://github.com/ShmuelRonen/ComfyUI_wav2lip/issues/36#issuecomment-2213971185 gives me

```
Error occurred when executing VHS_VideoCombine:

'function' object is not subscriptable


  File "D:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 523, in combine_video
    channels = audio['waveform'].size(1)
               ~~~~~^^^^^^^^^^^^
Queue size: 0
Extra options
```

**Comment by wenwenwennnnn** [comment]
![image](https://github.com/user-attachments/assets/d1551ab3-4f0f-4f24-9dc9-0cdc639e8f3f)
Repeated error reporting

**Comment by Kimthanh27** [comment]
File "E:\EMPTY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 156, in todo
    audio_data = process_audio(audio())
                               ^^^^^^^
TypeError: 'dict' object is not callable

Prompt executed in 3.92 seconds
can you pls help me^^
