### ISSUE TITLE
node not working

### ISSUE THREAD

**Issue by raochinmay6** [ShmuelRonen/ComfyUI_wav2lip#37]
![Screenshot (24)](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/160831464/4382a252-275b-4cc2-ae85-bdcd24c03821)

i try to fix but noting happan

**Comment by ShmuelRonen** [comment]
Send please the ComfyUI CMD log

**Comment by raochinmay6** [comment]
[comfyui.log](https://github.com/user-attachments/files/16120870/comfyui.log)
see this

**Comment by raochinmay6** [comment]
i am not good at coding so please explain in easy way

**Comment by raochinmay6** [comment]
![Screenshot (26)](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/160831464/bf30932c-53e0-4eca-96bd-3ff0d37af089)
see this

**Comment by raochinmay6** [comment]
also this 
![Screenshot (27)](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/160831464/2149bcba-029e-4431-ac60-78846110d82d)
[comfyui.log](https://github.com/user-attachments/files/16145566/comfyui.log)

**Comment by ShmuelRonen** [comment]
You can see here #36

**Comment by raochinmay6** [comment]
![Screenshot (29)](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/160831464/c1744a7e-69dc-4403-bafd-f5ca08b89326)
now this coming

**Comment by raochinmay6** [comment]
Exception during processing!!! 'function' object is not subscriptable
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 523, in combine_video
    channels = audio['waveform'].size(1)
               ~~~~~^^^^^^^^^^^^
TypeError: 'function' object is not subscriptable

Prompt executed in 114.03 seconds

**Comment by raochinmay6** [comment]
i alreay did videohelper suit part

**Comment by ShmuelRonen** [comment]
I can't solve problems with videohelper suit because it's not my node. You can try to replace the videohelper_suit custom node folder with this one and restart ComfyUI

![tell](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/80190186/923856d3-f73f-4ac6-92c3-ad719174ea2a)

**Comment by raochinmay6** [comment]
i already did it

**Comment by ShmuelRonen** [comment]
Delete all __pycache__ folder in all the folders inside ComfyUI_wav2lip and videohelper_suit and restart comfy

**Comment by Pancat007** [comment]
same error, it says I need another AudioToVHSAudio node, but I can't find it.
![image](https://github.com/user-attachments/assets/02849474-9ec9-43cd-bdc1-6b5905377988)

**Comment by ShmuelRonen** [comment]
So update it to the last version and use it instead
