### ISSUE TITLE
request - update for support audio input instead of VHS_AUDIO

### ISSUE THREAD

**Issue by whmc76** [ShmuelRonen/ComfyUI_wav2lip#38]
as you know VHS_AUDIO is not support and now it is audio output, pls update the node input thx

**Comment by giandre** [comment]
I thought I was the only one with this issue. Yes, please update this.

**Comment by ShmuelRonen** [comment]
This is just an informational message. Everything works fine

**Comment by giandre** [comment]
> This is just an informational message. Everything works fine

That is not correct. I am not able to run the queue at all. Nothing happens until this issue is resolved.
