### ISSUE TITLE
audio can't be routed

### ISSUE THREAD

**Issue by sammyjank** [ShmuelRonen/ComfyUI_wav2lip#40]
Hi, I can't connect the audio of the wav2lip node to anything. Other audio nodes are working fine, like the ones come with comfyui videohelper suite. Any suggestion?

**Comment by ShmuelRonen** [comment]
Hi. try to enter custom_nodes folder, delete the folder comfyui-videohelperSuite and reinstall it via the manager.

**Comment by sammyjank** [comment]
W

https://github.com/user-attachments/assets/c94210ec-ed6a-411c-9abf-aeb8f4badaab

ell,  i have done that twice already. Nothing works. Am I overseeing something? Attached a video. I'll put everything together from scratch one more time.

**Comment by sammyjank** [comment]
Issue persist. Reinstalled comfyui manually, also tried using the prebuild packages without any luck. Downloading your node as a zip from github or trying to install it via the manager ends up with the exact same thing.

**Comment by ShmuelRonen** [comment]
Following changes made to the ComfyUI code, the wav2lip node is now non-functional. I apologize for that.

**Comment by ShmuelRonen** [comment]
All problems solved! please delete ComfyUI_wav2lip folder from custom_nodes and reinstall via the manager.

**Comment by sushantpy** [comment]
still issue persist. please help. im also not getting ComfyUI-VideoHelperSuite-fix folder into repository after installing it.

**Comment by ShmuelRonen** [comment]
You don't need it any more

**Comment by sushantpy** [comment]
i got "ComfyUI-VideoHelperSuite-fix" this folder from your commit. by using this audio issue is solved now.
