### ISSUE TITLE
Is there a way to FRAME LOAD CAP with Audio Path node?

### ISSUE THREAD

**Issue by drelabre** [ShmuelRonen/ComfyUI_wav2lip#42]
I'm applying Wav2Lip at the end of a vid2vid workflow. I'm testing 24 frames of a 9 second video clip, but it appears that audio path is passing all 9 seconds worth of audio to wav2lip (i see more than 24 frames being passed to reactor face restore). The end result is a 8 sec video where the face speaks out the words in realtime, but the 24 frames of video are stretched over 9 seconds.

I tried loading audio with VHS node (which has a seconds cap), to no avail. Is there a way to apply a FRAME LOAD CAP input (ideally that can be connected to a central node)?. Feature request perhaps?

**Comment by ShmuelRonen** [comment]
You use repetitive mode?

**Comment by drelabre** [comment]
I've tried both Sequential and Repetitive (I don't know what that does, don't see any documentation on it). 

I found a work around. Audio from Load Video isn't recognized by Wav2Lip but seem to work if I pipe it through Audio to Legacy VHS_AUDIO node..

**Comment by ShmuelRonen** [comment]
wav2lip node is designed to work with the attached workflow. Please prepare a video in advance that allows you to create a repetitive loop and enter the sound file through the node provided in Workflow.

1. In sequential mode the movie is stretched to fit the length of the sound file. So facial movements may be slow.

2. In repetitive mode, if the movie is shorter than the sound file, it is inserted again and again until the sound file ends.

**Comment by drelabre** [comment]
Thanks for the response and the explanation. I was hoping to mitigate preprocessing video, but it seem unavoidable at this time. I will revert to the workflow you supplied.
