### ISSUE TITLE
wav2lip node parameters

### ISSUE THREAD

**Issue by sushantpy** [ShmuelRonen/ComfyUI_wav2lip#44]
basically in wav2lip node there is only 2 parameters that is "mode" and "face_detect_batch" 
but before update,  there was a more 3 parameters. those are "lipsync_intensity" , "smoothing_factor" and "framerate". 
i want those parameters but i cant get it because of update. please help me

**Comment by ShmuelRonen** [comment]
Sorry for that. but the current version is what it is.

**Comment by sushantpy** [comment]
is there any way where i can get those parameters???

**Comment by ShmuelRonen** [comment]
Sorry. but not.

**Comment by sushantpy** [comment]
okay fine. 
im facing one issue. im trying to lipsync a walking video of person.  In output, lipsync quality is not that much good. there is a dirtiness. how to make it look good??? 

for image to lipsync its working very good. but for video to lipsync its not that much good. 
can you please suggest me something , with that i can make smooth lipsync to video
