### ISSUE TITLE
Wav2Lip output video framerate issue (12 FPS input processed at 30 FPS)

### ISSUE THREAD

**Issue by madhuys** [ShmuelRonen/ComfyUI_wav2lip#47]
Hi,

Firstly, thanks a lot for providing this resource. I am having a minor challenge and was hoping you could help point me in the right direction.

I am working with a 24 FPS video, but I am using only every 2nd frame to achieve a 12 FPS video.

I am then passing this 12 FPS video to Wav2Lip for lip-sync processing. However, Wav2Lip seems to process the input at 30 FPS, adding extra frames and disrupting the flow.

For example:
>I input a 15-second video at 12 FPS (180 frames total).
>Wav2Lip returns a 15-second video but at 30 FPS, which has 450 frames, causing the flow to become inconsistent.

I have tested both:
>Repetitive input (smaller video looping).
>Sequential input (maintaining the same video length).
Neither approach has resolved the issue.

Question: Is there a way to set the input framerate to match the output framerate, or to otherwise ensure the output matches the original input framerate (12 FPS) without Wav2Lip modifying it to 30 FPS?

**Thanks in advance for your help.**

**Comment by ShmuelRonen** [comment]
Are you try to adjust the frame rate on video combine to 12 FPS?

**Comment by madhuys** [comment]
The video length increases as more frames are created. After running the Wav2Lip process, I used a "get frame size and count" node, and noticed the frame count was consistently much higher. Essentially, the number of frames in the video increases after processing.

how to replicate


input a 12 FPS source video frames + audio > count number of input frames > send to wav2lip> count output frames.

Increasing FPS in videocombine gives a very jerky output. 

doesn't match

**Comment by madhuys** [comment]
Have tested multiple times and can confirm the behaviour

feed a 100 /200 /300 frame video at differernt FPS. Wav2lip always creates a video with audio samples scaled to 30 fps. Total frames - four frames. four frames are somehow lost.

e.g. if i feed 100 frames at 10 fps - output is always 296 frames and very jerky. if i feed at 30 fps, much better output.

Interestingly, four frames are always lost. I'm not able to tell which frames they are, but I suspect the first four.

**Comment by ShmuelRonen** [comment]
The solution can only come from your side by converting your video to 30 FPS
