### ISSUE TITLE
how to show lips better like the video in youtube?

### ISSUE THREAD

**Issue by margo2130** [ShmuelRonen/ComfyUI_wav2lip#51]
hi, thank you for this model. i have a problem.
i use this 6 second video and i get this output:

https://github.com/user-attachments/assets/e3ac0a13-c295-4220-be99-ebd41286049d

https://github.com/user-attachments/assets/7afccd38-90fb-41c8-bde7-8b350d9d599f

now look at this YouTube video output in 7:47 second:

https://www.youtube.com/watch?v=ICSD76y4ooE
-------
- how can i make my video like that? look how her lip is so good with showing her teeth.
- how did he do it so good but for me it is bad?
workflow:
[workflow.json](https://github.com/user-attachments/files/17180169/workflow.json)

**Comment by ShmuelRonen** [comment]
Use ComfyUI-advancedLivePortrait for that

https://github.com/user-attachments/assets/85f39265-f0aa-4aaa-b5c4-0064676359e7
