### ISSUE TITLE
【Wav2Lip Node for ComfyUI】Conflicted Nodes (6)

### ISSUE THREAD

**Issue by Uncharted1234** [ShmuelRonen/ComfyUI_wav2lip#52]
【Wav2Lip Node for ComfyUI】Conflicted Nodes (6)
LoadAudio [ComfyUI-FishSpeech]
LoadAudio [ComfyUI-GPT_SoVITS]
LoadAudio [ComfyUI-Live2DViewer]
LoadAudio [ComfyUI-RVC]
LoadAudio [ComfyUI-WhisperX]
LoadAudio [ComfyUI]

**Comment by Uncharted1234** [comment]
Sorry newbie here. I had to roll back to my python from 3.11 to 3.10. I downgraded everything to try and make this plug in work and nothing works. I keep getting said prompt listed above as if I have those things...which I don't. What can I do to make this work?

**Comment by ShmuelRonen** [comment]
I have no idea

**Comment by Uncharted1234** [comment]
I solved it! So comfyui apparently is blocking third party people from github. I had to put "security_level = weak" in the ""...\ComfyUI\custom_nodes\ComfyUI-Manager\config.ini" file. I can now use your node.

**Comment by Uncharted1234** [comment]
Yikes...sorry to come back. Seems like when I try to pip install -r requirements.txt for other nodes like ReActor. Seems like Wav2lip breaks. Seems like one or the other works but not both. I am in the phase of deleting old nodes I don't use anymore in hopes of clearing out things. I ran through with chatgpt to fix a lot of issues like making sure everything else under the hood was fine with comfyui. I did a update comfy.bat file. I have tried uninstalling and re-installing this plug in with zero luck. Hit or miss depending on if I get it to work and then try to make something else work like live portrait. 

after update I checked the window prompt and saw this:

Warn!: WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

Warn!: IMPORT FAILED: nodes_audio.py
Warn!:
This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
Warn!: Please run the update script: update/update_comfyui.bat
Warn!:
Starting server

**Comment by ShmuelRonen** [comment]
It's works perfect

https://github.com/user-attachments/assets/d647f03d-898b-4253-9294-9e462bd52267

**Comment by Uncharted1234** [comment]
I am using the comfyui locally on my computer. What could I be the issue then? I got reactor and live portrait working now. 
![NotLoading1](https://github.com/user-attachments/assets/70838365-36a7-49d6-a86f-68943fdd8dc7)
![NotLoading2](https://github.com/user-attachments/assets/68e08def-f577-48cc-b2e8-1cf41df1d3b5)
![checkpoint](https://github.com/user-attachments/assets/0a3ae63c-4735-4d3e-ac91-88db458a0fa4)
![folderstructure](https://github.com/user-attachments/assets/a7b8fa6b-2eaa-49eb-a25a-1b5827054bf2)
