### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Wav2Lip\\checkpoints\\wav2lip_gan.pth'

### ISSUE THREAD

**Issue by signorinileandro** [ShmuelRonen/ComfyUI_wav2lip#6]
There is a hardcoded path in [wave2lip_node.py line 155 ](https://github.com/ShmuelRonen/ComfyUI_wav2lip/blob/main/Wav2Lip/wav2lip_node.py#L155C57-L155C58)

**Comment by ShmuelRonen** [comment]
Thanks!!
