### ISSUE TITLE
facerestore_models wrong path

### ISSUE THREAD

**Issue by signorinileandro** [ShmuelRonen/ComfyUI_wav2lip#7]
Currently, as it's defined in the node: https://github.com/ShmuelRonen/ComfyUI_wav2lip/blob/main/wav2lip.py#L170
ComfyUI is looking for facerestore models in `ComfyUI\models\facerestore_models`, not in `ComfyUI\custom_nodes\ComfyUI_wav2lip\models\facerestore_models`, as the readme says

**Comment by ShmuelRonen** [comment]
This is the path:

![models](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/80190186/a16b8ad3-793c-4984-9bc8-1a91fd666948)
