### ISSUE TITLE
Installation error after the last update

### ISSUE THREAD

**Issue by start-life** [ShmuelRonen/ComfyUI_wav2lip#8]
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-19 17:44:00.162589
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\zxcv\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\zxcv\ComfyUI_windows_portable\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

## Execute install/(de)activation script for 'C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
 Collecting tensorflow-gpu
   Downloading tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [44 lines of output]
[!]   Traceback (most recent call last):
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 35, in __init__
[!]       parsed = _parse_requirement(requirement_string)
[!]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 64, in parse_requirement
[!]       return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 82, in _parse_requirement
[!]       url, specifier, marker = _parse_requirement_details(tokenizer)
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 126, in _parse_requirement_details
[!]       marker = _parse_requirement_marker(
[!]                ^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
[!]       tokenizer.raise_syntax_error(
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_vendor\packaging\_tokenizer.py", line 165, in raise_syntax_error
[!]       raise ParserSyntaxError(
[!]   setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
[!]       python_version>"3.7"
[!]                     ^
[!]
[!]   The above exception was the direct cause of the following exception:
[!]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\z5050\AppData\Local\Temp\pip-install-40ldhl6k\tensorflow-gpu_6e3463bdc3604b3083c47fe7cf41b4bd\setup.py", line 40, in <module>
[!]       setuptools.setup()
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\__init__.py", line 103, in setup
[!]       _install_setup_requires(attrs)
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\__init__.py", line 74, in _install_setup_requires
[!]       dist.parse_config_files(ignore_option_errors=True)
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\dist.py", line 633, in parse_config_files
[!]       self._finalize_requires()
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\dist.py", line 368, in _finalize_requires
[!]       self._normalize_requires()
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\dist.py", line 383, in _normalize_requires
[!]       self.install_requires = list(map(str, _reqs.parse(install_requires)))
[!]                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 37, in __init__
[!]       raise InvalidRequirement(str(e)) from e
[!]   setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
[!]       python_version>"3.7"
[!]                     ^
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip

## Execute install/(de)activation script for 'C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com

## Execute install/(de)activation script for 'C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
 Collecting gfpgan
   Downloading gfpgan-1.3.8-py3-none-any.whl.metadata (12 kB)
  Collecting facexlib>=0.2.5 (from gfpgan)
   Downloading facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
                Collecting filterpy (from facexlib>=0.2.5->gfpgan)
   Downloading filterpy-1.4.5.zip (177 kB)
      -------------------------------------- 178.0/178.0 kB 1.2 MB/s eta 0:00:00
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\z5050\AppData\Local\Temp\pip-install-gvce3azi\filterpy_c4b9ba98276b46cfb55e3c3e555f2013\setup.py", line 4, in <module>
[!]       import filterpy
[!]   ModuleNotFoundError: No module named 'filterpy'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip

## Execute install/(de)activation script for 'C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
 Collecting realesrgan
   Downloading realesrgan-0.3.0-py3-none-any.whl.metadata (17 kB)
  Collecting facexlib>=0.2.5 (from realesrgan)
   Downloading facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
 Collecting gfpgan>=1.3.5 (from realesrgan)
   Downloading gfpgan-1.3.8-py3-none-any.whl.metadata (12 kB)
                Collecting filterpy (from facexlib>=0.2.5->realesrgan)
   Downloading filterpy-1.4.5.zip (177 kB)
      -------------------------------------- 178.0/178.0 kB 1.3 MB/s eta 0:00:00
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\z5050\AppData\Local\Temp\pip-install-tfhr06ln\filterpy_30a6444468ec445b8e68751590829b88\setup.py", line 4, in <module>
[!]       import filterpy
[!]   ModuleNotFoundError: No module named 'filterpy'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip

[ComfyUI-Manager] Startup script completed.

### **I'm trying to install the missing package and this is the error**

C:\zxcv\ComfyUI_windows_portable>python_embeded\python.exe -m pip install filterpy
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting filterpy
  Downloading filterpy-1.4.5.zip (177 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.0/178.0 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\z5050\AppData\Local\Temp\pip-install-o6195xxz\filterpy_07235db6402447009f2a2458e0785499\setup.py", line 4, in <module>
          import filterpy
      ModuleNotFoundError: No module named 'filterpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ShmuelRonen** [comment]
Update ComfyUI_wav2lip with git pull
